version: 1.0
provider:
  name: openfaas
  gateway: http://10.230.166.1:8080
functions:
  h-hello-world:
    lang: hybrid-py
    handler: ./h-hello-world
    image: jialianghuang/h-hello-world:latest
    limits:
      memory: 128M
      cpu: 1
    port: 5001
    environment:
      port: 9001